### PR TITLE
CircleCI config

### PR DESCRIPTION
**Pull request by scttnlsn**

### CODE REVIEW

**Comment by scttnlsn** [comment]
@pauledwardmitchell Ready to go.  All tests passing!

**Comment by scttnlsn** [comment]
Note that I had to upgrade the Ruby version to 2.3.8 since CircleCI does not support 2.3.1

**Comment by pauledwardmitchell** [comment]
@scttnlsn Fantastic.  I'll merge this ASAP.  Thanks much.

**Comment by pauledwardmitchell** [comment]
@scttnlsn I pulled down this PR and switched to ruby 2.3.8 - and am receiving the following error when I run `bundle` or `bundle exec rspec`.

```
marvl3 (circleci) :> bundle
rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  2.1.5
  2.3.0
  2.3.1
  2.6.3
```

Thoughts on what I should try next?

**Comment by scttnlsn** [comment]
@pauledwardmitchell You'll need to run `gem install bundler` and then `bundle install`

**Pull request merged**
