### PR TITLE
Upgrade to Webpacker v4

### PR DESCRIPTION
**Pull request by scttnlsn**

### CODE REVIEW

**Comment by scttnlsn** [comment]
Hmm, looks like the CircleCI environment is running out of memory when running `rake webpacker:compile`.

**Comment by scttnlsn** [comment]
Not really sure what to do about this.  @pauledwardmitchell Maybe you could open a support ticket like they mention here: https://circleci.com/docs/2.0/optimizations/#resource-class  Maybe we can allocate a bit more memory to the step that runs the compilation.

**Comment by pauledwardmitchell** [comment]
@scttnlsn ok - I’ll check it out and submit the ticket.
It seems like a CircleCI problem though? Everything compiles correctly for you in the dev environment with the new configuration? 
(I’ve not pulled it down yet - just wanted to understand your comments and respond to you tonight.)

**Comment by scttnlsn** [comment]
Yeah, everything is working for me locally - something specific to the CI environment as far as I can tell

**Pull request merged**
